version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SERVER_ADDRESS=:5000
      - SERVER_READ_TIMEOUT=15s
      - SERVER_WRITE_TIMEOUT=15s
      - SERVER_IDLE_TIMEOUT=30s
      - MAX_CONNS=99
      - SPACEX_URL=https://api.spacexdata.com/v4
    depends_on:
      - db
    networks:
      - spacenet

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=space
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spacenet

volumes:
  postgres_data:

networks:
  spacenet:
    driver: bridge